### ISSUE TITLE
Not Workingf Internal CSS in Python Advanced Course

### ISSUE THREAD

**Issue by tutorialswithsanju** [ManyamSanjayKumarReddy/Open-Source-Tutorials-with-Sanju-Website#1]
Please check the Internal Styling not Working

**Comment by tutorialswithsanju** [comment]
Styling based on the Key Frame is error

**Comment by ManyamSanjayKumarReddy** [comment]
Working on this We will keep you updated

**Comment by ManyamSanjayKumarReddy** [comment]
![liked](https://github.com/ManyamSanjayKumarReddy/Open-Source-Tutorials-with-Sanju-Website/assets/94047241/c9eaa734-0950-476d-a735-be1ed651893a)
We have fixed the error please check now
